version: "3"

services:
  app:
    container_name: canvas_bot
    build: .
    restart: on-failure
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./merges:/app/merges

    env_file: .env
    # environment:
    #   - CANVAS_TOKEN=<Seu token do canvas>
    #   - TELEGRAM_TOKEN=<Seu token do telegram>
    #   - TELEGRAM_CHAT_ID=<Seu chat_id do telegram>
    #   - AMBIENTE=prod

    # O ambiente 'dev' desabilita a atualizacao automatica do cache
    #   - AMBIENTE=dev
