version: "3"

services:
  app:
    container_name: canvas_bot
    build: .
    env_file: .env
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./merges:/app/merges
    # environment:
    #   - CANVAS_TOKEN=<Seu token do canvas>
    #   - TELEGRAM_TOKEN=<Seu token do telegram>
    #   - TELEGRAM_CHAT_ID=<Seu chat_id do telegram>
    #   - AMBIENTE=prod
    #   - TZ=America/Sao_Paulo
